[workspace]
members = [
    'node',
    'pallets/*',
    'runtime',
    'primitives'
]
[profile.release]
panic = 'unwind'

[patch.crates-io.crypto-mac]
git = "https://github.com/RustCrypto/traits.git"
tag = "crypto-mac-v0.7.0"