name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main] 

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-18.04
    env:
      DOCKER_REPO: atactr/automata
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate tags
        run: |
          echo 'DOCKER_TAGS<<EOF' >> $GITHUB_ENV
          echo "${DOCKER_REPO}:${GITHUB_SHA::8}" >> $GITHUB_ENV
          if [ "${GITHUB_REF}" = "ref/heads/main" ]
          then
            echo "${DOCKER_REPO}:latest" >> $GITHUB_ENV
          fi
          echo 'EOF' >> $GITHUB_ENV
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          cache-from: ${{ env.DOCKER_REPO }}:latest
          cache-to: type=inline,mode=max
          tags: |
            ${{ env.DOCKER_TAGS }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}