name: Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main] 

jobs:
  build_and_push:
    name: Build and Push
    runs-on: ubuntu-18.04
    env:
      DOCKER_REPO: atactr/automata
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Generate tags
        run: |
          echo 'DOCKER_TAGS<<EOF' >> $GITHUB_ENV
          echo "${DOCKER_REPO}:${GITHUB_SHA::8}" >> $GITHUB_ENV
          if [ "${GITHUB_REF}" = "ref/heads/main" ]
          then
            echo "${DOCKER_REPO}:latest" >> $GITHUB_ENV
          fi
          echo 'EOF' >> $GITHUB_ENV
      - name: Build with cache and push images
        uses: docker/build-push-action@v2
        id: docker_build
        with:
          push: true
          cache-from: |
            type=registry,ref=${{ env.DOCKER_REPO }}:builder
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=local,dest=/tmp/.buildx-cache-new,mode=max
          tags: |
            ${{ env.DOCKER_TAGS }}
      - name: Update registry cache
        uses: docker/build-push-action@v2
        if: github.ref == 'refs/heads/main'
        with:
          cache-from: |
            type=registry,ref=${{ env.DOCKER_REPO }}:builder
            type=local,src=/tmp/.buildx-cache
          cache-to: |
            type=registry,ref=${{ env.DOCKER_REPO }}:builder,mode=max
      - # FIXME: a workaround before these issues got fixed
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}